[helpers]

[default]
depends = []

[default.files]
"assets/images/honkai_everyone.png" = { target = "~/.assets/images/honkai_everyone.png", type = "symbolic" }
"assets/images/silver_wolf.png" = { target = "~/.assets/images/silver_wolf.png", type = "symbolic" }

"includes/windows/powershell/profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"includes/windows/git/.gitconfig" = "~/.gitconfig"
"includes/windows/git/.gitignore_global" = "~/.gitignore_global"
"includes/windows/autohotkey/default.ahk" = "~/.config/autohotkey/default.ahk"

"includes/home/vim/.ideavimrc" = "~/.ideavimrc"
"includes/home/git/.tigrc" = "~/.tigrc"

"includes/home/terminal/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"includes/home/terminal/wezterm/keybindings.lua" = "~/.config/wezterm/keybindings.lua"
"includes/windows/wezterm/keybindings.lua" = "~/.config/wezterm/local/keybindings.lua"
"includes/windows/wezterm/images.lua" = "~/.config/wezterm/local/images.lua"

"includes/home/dev/ai/gemini/settings.json" = "~/.gemini/settings.json"

[default.variables]

[settings]
default_target_type = "automatic"
