[helpers]

[default]
depends = []

[default.files]
"assets/images/honkai_everyone.png" = { target = "~/.assets/images/honkai_everyone.png", type = "symbolic" }
"assets/images/silver_wolf.png" = { target = "~/.assets/images/silver_wolf.png", type = "symbolic" }

"modules/windows/powershell/profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"modules/windows/git/.gitconfig" = "~/.gitconfig"
"modules/windows/git/.gitignore_global" = "~/.gitignore_global"
"modules/windows/autohotkey/default.ahk" = "~/.config/autohotkey/default.ahk"

"modules/home/dev/jetbrains/.ideavimrc" = "~/.ideavimrc"
"modules/home/git/.tigrc" = "~/.tigrc"

"modules/home/terminal/wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"
"modules/home/terminal/wezterm/keybindings.lua" = "~/.config/wezterm/keybindings.lua"
"modules/windows/wezterm/keybindings.lua" = "~/.config/wezterm/local/keybindings.lua"
"modules/windows/wezterm/images.lua" = "~/.config/wezterm/local/images.lua"

"modules/home/ai/gemini/settings.json" = "~/.gemini/settings.json"

"modules/home/dev/vscode/keybindings.json" = "~/AppData/Roaming/Code/User/keybindings.json"

"modules/windows/corvusskk/config.xml" = "~/AppData/Roaming/CorvusSKK/config.xml"

[default.variables]

[settings]
default_target_type = "automatic"
